// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// obsAffectation_F
IntegerVector obsAffectation_F(NumericMatrix& protos, NumericMatrix& x_new);
RcppExport SEXP _SOMbrero_obsAffectation_F(SEXP protosSEXP, SEXP x_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type protos(protosSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type x_new(x_newSEXP);
    rcpp_result_gen = Rcpp::wrap(obsAffectation_F(protos, x_new));
    return rcpp_result_gen;
END_RCPP
}
// scaleMatrix
NumericMatrix scaleMatrix(NumericMatrix& mat, std::string scaling);
RcppExport SEXP _SOMbrero_scaleMatrix(SEXP matSEXP, SEXP scalingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::string >::type scaling(scalingSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleMatrix(mat, scaling));
    return rcpp_result_gen;
END_RCPP
}
// trainNumeric
void trainNumeric(NumericMatrix prototypes, List parameters, NumericMatrix x_data, NumericMatrix norm_x_data, List backup, List the_dist);
RcppExport SEXP _SOMbrero_trainNumeric(SEXP prototypesSEXP, SEXP parametersSEXP, SEXP x_dataSEXP, SEXP norm_x_dataSEXP, SEXP backupSEXP, SEXP the_distSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type prototypes(prototypesSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type norm_x_data(norm_x_dataSEXP);
    Rcpp::traits::input_parameter< List >::type backup(backupSEXP);
    Rcpp::traits::input_parameter< List >::type the_dist(the_distSEXP);
    trainNumeric(prototypes, parameters, x_data, norm_x_data, backup, the_dist);
    return R_NilValue;
END_RCPP
}
// trainKorresp
void trainKorresp(NumericMatrix prototypes, List parameters, NumericMatrix x_data, NumericMatrix norm_x_data, List backup, List the_dist);
RcppExport SEXP _SOMbrero_trainKorresp(SEXP prototypesSEXP, SEXP parametersSEXP, SEXP x_dataSEXP, SEXP norm_x_dataSEXP, SEXP backupSEXP, SEXP the_distSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type prototypes(prototypesSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type norm_x_data(norm_x_dataSEXP);
    Rcpp::traits::input_parameter< List >::type backup(backupSEXP);
    Rcpp::traits::input_parameter< List >::type the_dist(the_distSEXP);
    trainKorresp(prototypes, parameters, x_data, norm_x_data, backup, the_dist);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SOMbrero_obsAffectation_F", (DL_FUNC) &_SOMbrero_obsAffectation_F, 2},
    {"_SOMbrero_scaleMatrix", (DL_FUNC) &_SOMbrero_scaleMatrix, 2},
    {"_SOMbrero_trainNumeric", (DL_FUNC) &_SOMbrero_trainNumeric, 6},
    {"_SOMbrero_trainKorresp", (DL_FUNC) &_SOMbrero_trainKorresp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_SOMbrero(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
