# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

obsAffectation_F <- function(BB, CC) {
    .Call(`_SOMbrero_obsAffectation_F`, BB, CC)
}

scaleMatrix <- function(mat, scaling) {
    .Call(`_SOMbrero_scaleMatrix`, mat, scaling)
}

trainNumeric <- function(prototypes, parameters, x_data, norm_x_data, backup, the_dist) {
    invisible(.Call(`_SOMbrero_trainNumeric`, prototypes, parameters, x_data, norm_x_data, backup, the_dist))
}

trainKorresp <- function(prototypes, parameters, x_data, norm_x_data, backup, the_dist) {
    invisible(.Call(`_SOMbrero_trainKorresp`, prototypes, parameters, x_data, norm_x_data, backup, the_dist))
}

